version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    user: "1000:1000" # Use host user's UID:GID for permissions
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8888:8888"   # FIXED (map host 8888 -> container 5000)
    environment:
      - MONGO_URI=mongodb://localhost:27017/complaint_system?authSource=admin
      - DOCKER_ENV=true
      - JWT_SECRET_KEY=accs_8xmP9$vL2@nQ5&hR7*jK3
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongodb_data:
    name: accs_mongodb_data

networks:
  app-network:
    driver: bridge
